server:
  port:
    8080

spring:
  main:
    banner-mode: 'off'
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/recrutemeddb
    username: XX
    password: XX

  flyway:
    baseline-on-migrate: true

---

spring:
  profiles: dev

---

spring:
  profiles: ldev

---

spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:dbldev;MODE=PostgreSQL
    dirverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

    h2:
      console.enabled: true

    jpa:
      properties:
        hibernate:
          default_schema: car-rent
          type: trace
          temp:
            use_jdbc_metadata_defaults: false
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: none
                create-target: create-h2.sql
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      use_sql_comments: true
      format_sql: true
      hibernate:
        ddl-auto: none

      flyway:
        locations: classpath:db/migration/h2

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

